export type NeuprintAxes = {
  analyticity: number;
  flow: number;
  metacognition: number;
  authenticity: number;
};

export type RoleConfig = {
  role_code: string;
  job_id: string;
  onet_code: string;
  oecd_core_skills: string[];
  neuprint_axes_weights: NeuprintAxes;
  min_requirements: {
    arc_level: number;
    analyticity?: number;
    flow?: number;
    metacognition?: number;
    authenticity?: number;
  };
};

/**
 * NeuPrint Role Configs Full v3.0
 * - Generated from roleConfigs_full_v1.ts with all TO_VALIDATE entries resolved to concrete O*NET proxy codes
 * - neuprint_axes_weights recomputed from uploaded O*NET Skills.txt + Abilities.txt using IM scale rows
 * - computed weights are lightly smoothed with v1 priors, then normalized to sum to 1.000 for each role
 */

export const ROLE_CONFIGS_FULL_V3: RoleConfig[] = [
  {
    role_code: "STRATEGY_ANALYST",
    job_id: "strategy_analyst",
    onet_code: "13-1111.00",
    oecd_core_skills: ["Complex Problem Solving", "Systems Thinking", "Decision Making"],
    neuprint_axes_weights: {
      analyticity: 0.314,
      flow: 0.187,
      metacognition: 0.271,
      authenticity: 0.228,
    },
    min_requirements: { arc_level: 4, analyticity: 0.6 },
  },
  {
    role_code: "MANAGEMENT_ANALYST",
    job_id: "management_analyst",
    onet_code: "13-1111.00",
    oecd_core_skills: ["Systems Thinking", "Decision Making", "Communication"],
    neuprint_axes_weights: {
      analyticity: 0.307,
      flow: 0.187,
      metacognition: 0.271,
      authenticity: 0.235,
    },
    min_requirements: { arc_level: 4, analyticity: 0.6 },
  },
  {
    role_code: "POLICY_ANALYST",
    job_id: "policy_analyst",
    onet_code: "19-3094.00",
    oecd_core_skills: ["Critical Thinking", "Judgment", "Systems Analysis"],
    neuprint_axes_weights: {
      analyticity: 0.304,
      flow: 0.181,
      metacognition: 0.284,
      authenticity: 0.231,
    },
    min_requirements: { arc_level: 4, analyticity: 0.6 },
  },
  {
    role_code: "ECONOMIC_RESEARCHER",
    job_id: "economic_researcher",
    onet_code: "19-3011.00",
    oecd_core_skills: ["Critical Thinking", "Data Analysis", "Systems Thinking"],
    neuprint_axes_weights: {
      analyticity: 0.319,
      flow: 0.182,
      metacognition: 0.273,
      authenticity: 0.226,
    },
    min_requirements: { arc_level: 4, analyticity: 0.6 },
  },
  {
    role_code: "FINANCIAL_ANALYST",
    job_id: "financial_analyst",
    onet_code: "13-2051.00",
    oecd_core_skills: ["Critical Thinking", "Monitoring", "Decision Making"],
    neuprint_axes_weights: {
      analyticity: 0.355,
      flow: 0.035,
      metacognition: 0.575,
      authenticity: 0.035,
    },
    min_requirements: { arc_level: 4, analyticity: 0.6 },
  },
  {
    role_code: "RISK_ANALYST",
    job_id: "risk_analyst",
    onet_code: "13-2054.00",
    oecd_core_skills: ["Judgment", "Complex Problem Solving", "Monitoring"],
    neuprint_axes_weights: {
      analyticity: 0.355,
      flow: 0.035,
      metacognition: 0.575,
      authenticity: 0.035,
    },
    min_requirements: { arc_level: 4, analyticity: 0.6 },
  },
  {
    role_code: "COMPLIANCE_OFFICER",
    job_id: "compliance_officer",
    onet_code: "13-1041.00",
    oecd_core_skills: ["Monitoring", "Judgment", "Communication"],
    neuprint_axes_weights: {
      analyticity: 0.278,
      flow: 0.197,
      metacognition: 0.281,
      authenticity: 0.244,
    },
    min_requirements: { arc_level: 4, analyticity: 0.6 },
  },
  {
    role_code: "INTERNAL_AUDITOR",
    job_id: "internal_auditor",
    onet_code: "13-2011.00",
    oecd_core_skills: ["Monitoring", "Critical Thinking", "Decision Making"],
    neuprint_axes_weights: {
      analyticity: 0.297,
      flow: 0.199,
      metacognition: 0.28,
      authenticity: 0.224,
    },
    min_requirements: { arc_level: 4, analyticity: 0.6 },
  },
  {
    role_code: "DATA_ANALYST",
    job_id: "data_analyst",
    onet_code: "15-2051.00",
    oecd_core_skills: ["Critical Thinking", "Information Processing", "Active Learning"],
    neuprint_axes_weights: {
      analyticity: 0.351,
      flow: 0.322,
      metacognition: 0.292,
      authenticity: 0.035,
    },
    min_requirements: { arc_level: 3, analyticity: 0.55, flow: 0.55 },
  },
  {
    role_code: "DATA_SCIENTIST",
    job_id: "data_scientist",
    onet_code: "15-2051.01",
    oecd_core_skills: ["Critical Thinking", "Complex Problem Solving", "Active Learning"],
    neuprint_axes_weights: {
      analyticity: 0.307,
      flow: 0.227,
      metacognition: 0.246,
      authenticity: 0.22,
    },
    min_requirements: { arc_level: 3, analyticity: 0.55, flow: 0.55 },
  },
  {
    role_code: "BUSINESS_INTELLIGENCE_ANALYST",
    job_id: "business_intelligence_analyst",
    onet_code: "15-2051.01",
    oecd_core_skills: ["Critical Thinking", "Information Processing", "Decision Making"],
    neuprint_axes_weights: {
      analyticity: 0.299,
      flow: 0.235,
      metacognition: 0.246,
      authenticity: 0.22,
    },
    min_requirements: { arc_level: 3, analyticity: 0.55, flow: 0.55 },
  },
  {
    role_code: "MACHINE_LEARNING_ANALYST",
    job_id: "machine_learning_analyst",
    onet_code: "15-2051.00",
    oecd_core_skills: ["Complex Problem Solving", "Active Learning", "Systems Thinking"],
    neuprint_axes_weights: {
      analyticity: 0.601,
      flow: 0.072,
      metacognition: 0.292,
      authenticity: 0.035,
    },
    min_requirements: { arc_level: 3, analyticity: 0.55, flow: 0.55 },
  },
  {
    role_code: "STATISTICIAN",
    job_id: "statistician",
    onet_code: "15-2041.00",
    oecd_core_skills: ["Critical Thinking", "Information Processing", "Analytical Thinking"],
    neuprint_axes_weights: {
      analyticity: 0.312,
      flow: 0.239,
      metacognition: 0.235,
      authenticity: 0.214,
    },
    min_requirements: { arc_level: 3, flow: 0.55 },
  },
  {
    role_code: "OPERATIONS_RESEARCH_ANALYST",
    job_id: "operations_research_analyst",
    onet_code: "15-2031.00",
    oecd_core_skills: ["Complex Problem Solving", "Systems Analysis", "Decision Making"],
    neuprint_axes_weights: {
      analyticity: 0.328,
      flow: 0.221,
      metacognition: 0.24,
      authenticity: 0.211,
    },
    min_requirements: { arc_level: 3, analyticity: 0.55, flow: 0.55 },
  },
  {
    role_code: "INFORMATION_SECURITY_ANALYST",
    job_id: "information_security_analyst",
    onet_code: "15-1212.00",
    oecd_core_skills: ["Monitoring", "Critical Thinking", "Systems Analysis"],
    neuprint_axes_weights: {
      analyticity: 0.31,
      flow: 0.238,
      metacognition: 0.239,
      authenticity: 0.213,
    },
    min_requirements: { arc_level: 3, analyticity: 0.55, flow: 0.55 },
  },
  {
    role_code: "SOFTWARE_ENGINEER",
    job_id: "software_engineer",
    onet_code: "15-1252.00",
    oecd_core_skills: ["Complex Problem Solving", "Systems Analysis", "Active Learning"],
    neuprint_axes_weights: {
      analyticity: 0.302,
      flow: 0.241,
      metacognition: 0.247,
      authenticity: 0.21,
    },
    min_requirements: { arc_level: 4, analyticity: 0.55 },
  },
  {
    role_code: "SYSTEMS_ARCHITECT",
    job_id: "systems_architect",
    onet_code: "15-1241.00",
    oecd_core_skills: ["Systems Analysis", "Complex Problem Solving", "Decision Making"],
    neuprint_axes_weights: {
      analyticity: 0.31,
      flow: 0.229,
      metacognition: 0.245,
      authenticity: 0.216,
    },
    min_requirements: { arc_level: 4, analyticity: 0.55 },
  },
  {
    role_code: "CLOUD_ENGINEER",
    job_id: "cloud_engineer",
    onet_code: "15-1244.00",
    oecd_core_skills: ["Systems Analysis", "Monitoring", "Complex Problem Solving"],
    neuprint_axes_weights: {
      analyticity: 0.306,
      flow: 0.247,
      metacognition: 0.244,
      authenticity: 0.203,
    },
    min_requirements: { arc_level: 4, analyticity: 0.55 },
  },
  {
    role_code: "DEVOPS_ENGINEER",
    job_id: "devops_engineer",
    onet_code: "15-1244.00",
    oecd_core_skills: ["Monitoring", "Systems Analysis", "Time Sharing"],
    neuprint_axes_weights: {
      analyticity: 0.298,
      flow: 0.255,
      metacognition: 0.244,
      authenticity: 0.203,
    },
    min_requirements: { arc_level: 4, analyticity: 0.55 },
  },
  {
    role_code: "NETWORK_ARCHITECT",
    job_id: "network_architect",
    onet_code: "15-1241.00",
    oecd_core_skills: ["Systems Analysis", "Complex Problem Solving", "Monitoring"],
    neuprint_axes_weights: {
      analyticity: 0.31,
      flow: 0.229,
      metacognition: 0.245,
      authenticity: 0.216,
    },
    min_requirements: { arc_level: 4, analyticity: 0.55 },
  },
  {
    role_code: "QA_ENGINEER",
    job_id: "qa_engineer",
    onet_code: "15-1253.00",
    oecd_core_skills: ["Monitoring", "Critical Thinking", "Decision Making"],
    neuprint_axes_weights: {
      analyticity: 0.291,
      flow: 0.245,
      metacognition: 0.254,
      authenticity: 0.21,
    },
    min_requirements: { arc_level: 4, analyticity: 0.55 },
  },
  {
    role_code: "SAFETY_SYSTEMS_ENGINEER",
    job_id: "safety_systems_engineer",
    onet_code: "17-2111.00",
    oecd_core_skills: ["Monitoring", "Systems Analysis", "Judgment"],
    neuprint_axes_weights: {
      analyticity: 0.288,
      flow: 0.245,
      metacognition: 0.252,
      authenticity: 0.215,
    },
    min_requirements: { arc_level: 4, analyticity: 0.55 },
  },
  {
    role_code: "PRODUCT_MANAGER",
    job_id: "product_manager",
    onet_code: "11-2021.00",
    oecd_core_skills: ["Complex Problem Solving", "Communication", "Decision Making"],
    neuprint_axes_weights: {
      analyticity: 0.253,
      flow: 0.219,
      metacognition: 0.248,
      authenticity: 0.28,
    },
    min_requirements: { arc_level: 3, authenticity: 0.5 },
  },
  {
    role_code: "SERVICE_DESIGNER",
    job_id: "service_designer",
    onet_code: "15-1255.00",
    oecd_core_skills: ["Communication", "Systems Thinking", "Active Learning"],
    neuprint_axes_weights: {
      analyticity: 0.316,
      flow: 0.06,
      metacognition: 0.292,
      authenticity: 0.332,
    },
    min_requirements: { arc_level: 3, authenticity: 0.55 },
  },
  {
    role_code: "UX_PLANNER",
    job_id: "ux_planner",
    onet_code: "15-1255.00",
    oecd_core_skills: ["Communication", "Cognitive Flexibility", "Critical Thinking"],
    neuprint_axes_weights: {
      analyticity: 0.321,
      flow: 0.31,
      metacognition: 0.045,
      authenticity: 0.324,
    },
    min_requirements: { arc_level: 3, authenticity: 0.5 },
  },
  {
    role_code: "BUSINESS_DEVELOPER",
    job_id: "business_developer",
    onet_code: "11-2022.00",
    oecd_core_skills: ["Communication", "Decision Making", "Systems Thinking"],
    neuprint_axes_weights: {
      analyticity: 0.264,
      flow: 0.221,
      metacognition: 0.241,
      authenticity: 0.274,
    },
    min_requirements: { arc_level: 3, authenticity: 0.5 },
  },
  {
    role_code: "INNOVATION_MANAGER",
    job_id: "innovation_manager",
    onet_code: "13-1111.00",
    oecd_core_skills: ["Complex Problem Solving", "Active Learning", "Communication"],
    neuprint_axes_weights: {
      analyticity: 0.267,
      flow: 0.21,
      metacognition: 0.243,
      authenticity: 0.28,
    },
    min_requirements: { arc_level: 3, authenticity: 0.5 },
  },
  {
    role_code: "R_AND_D_PLANNER",
    job_id: "r_and_d_planner",
    onet_code: "11-9041.00",
    oecd_core_skills: ["Complex Problem Solving", "Systems Thinking", "Active Learning"],
    neuprint_axes_weights: {
      analyticity: 0.27,
      flow: 0.22,
      metacognition: 0.247,
      authenticity: 0.263,
    },
    min_requirements: { arc_level: 3, authenticity: 0.5 },
  },
  {
    role_code: "NEW_VENTURE_STRATEGIST",
    job_id: "new_venture_strategist",
    onet_code: "13-1111.00",
    oecd_core_skills: ["Decision Making", "Complex Problem Solving", "Communication"],
    neuprint_axes_weights: {
      analyticity: 0.272,
      flow: 0.212,
      metacognition: 0.241,
      authenticity: 0.275,
    },
    min_requirements: { arc_level: 3, authenticity: 0.5 },
  },
  {
    role_code: "TEACHER",
    job_id: "teacher",
    onet_code: "25-2021.00",
    oecd_core_skills: ["Communication", "Learning to Learn", "Judgment"],
    neuprint_axes_weights: {
      analyticity: 0.244,
      flow: 0.205,
      metacognition: 0.295,
      authenticity: 0.256,
    },
    min_requirements: { arc_level: 3, metacognition: 0.5, authenticity: 0.6 },
  },
  {
    role_code: "PROFESSOR",
    job_id: "professor",
    onet_code: "25-1194.00",
    oecd_core_skills: ["Communication", "Critical Thinking", "Learning to Learn"],
    neuprint_axes_weights: {
      analyticity: 0.247,
      flow: 0.203,
      metacognition: 0.295,
      authenticity: 0.255,
    },
    min_requirements: { arc_level: 3, metacognition: 0.5 },
  },
  {
    role_code: "INSTRUCTIONAL_DESIGNER",
    job_id: "instructional_designer",
    onet_code: "25-9031.00",
    oecd_core_skills: ["Communication", "Systems Thinking", "Learning to Learn"],
    neuprint_axes_weights: {
      analyticity: 0.247,
      flow: 0.203,
      metacognition: 0.288,
      authenticity: 0.262,
    },
    min_requirements: { arc_level: 3, metacognition: 0.5, authenticity: 0.55 },
  },
  {
    role_code: "EDUCATION_CONSULTANT",
    job_id: "education_consultant",
    onet_code: "25-9031.00",
    oecd_core_skills: ["Communication", "Judgment", "Learning to Learn"],
    neuprint_axes_weights: {
      analyticity: 0.244,
      flow: 0.203,
      metacognition: 0.298,
      authenticity: 0.255,
    },
    min_requirements: { arc_level: 3, metacognition: 0.5 },
  },
  {
    role_code: "RESEARCH_SCIENTIST",
    job_id: "research_scientist",
    onet_code: "19-2099.00",
    oecd_core_skills: ["Critical Thinking", "Active Learning", "Systems Analysis"],
    neuprint_axes_weights: {
      analyticity: 0.574,
      flow: 0.042,
      metacognition: 0.332,
      authenticity: 0.052,
    },
    min_requirements: { arc_level: 3, analyticity: 0.55, metacognition: 0.5 },
  },
  {
    role_code: "RESEARCH_COORDINATOR",
    job_id: "research_coordinator",
    onet_code: "11-9121.01",
    oecd_core_skills: ["Monitoring", "Communication", "Active Learning"],
    neuprint_axes_weights: {
      analyticity: 0.257,
      flow: 0.205,
      metacognition: 0.287,
      authenticity: 0.251,
    },
    min_requirements: { arc_level: 3, metacognition: 0.5 },
  },
  {
    role_code: "ACADEMIC_ADVISOR",
    job_id: "academic_advisor",
    onet_code: "21-1012.00",
    oecd_core_skills: ["Communication", "Judgment", "Learning to Learn"],
    neuprint_axes_weights: {
      analyticity: 0.242,
      flow: 0.2,
      metacognition: 0.297,
      authenticity: 0.261,
    },
    min_requirements: { arc_level: 3, metacognition: 0.5 },
  },
  {
    role_code: "COUNSELOR",
    job_id: "counselor",
    onet_code: "21-1014.00",
    oecd_core_skills: ["Communication", "Judgment", "Social Perceptiveness"],
    neuprint_axes_weights: {
      analyticity: 0.221,
      flow: 0.19,
      metacognition: 0.271,
      authenticity: 0.318,
    },
    min_requirements: { arc_level: 4, authenticity: 0.6 },
  },
  {
    role_code: "CLINICAL_PSYCHOLOGIST",
    job_id: "clinical_psychologist",
    onet_code: "19-3033.00",
    oecd_core_skills: ["Judgment", "Critical Thinking", "Social Perceptiveness"],
    neuprint_axes_weights: {
      analyticity: 0.229,
      flow: 0.19,
      metacognition: 0.273,
      authenticity: 0.308,
    },
    min_requirements: { arc_level: 4, authenticity: 0.6 },
  },
  {
    role_code: "SCHOOL_PSYCHOLOGIST",
    job_id: "school_psychologist",
    onet_code: "19-3034.00",
    oecd_core_skills: ["Communication", "Judgment", "Social Perceptiveness"],
    neuprint_axes_weights: {
      analyticity: 0.224,
      flow: 0.193,
      metacognition: 0.271,
      authenticity: 0.312,
    },
    min_requirements: { arc_level: 4, authenticity: 0.6 },
  },
  {
    role_code: "SOCIAL_WORKER",
    job_id: "social_worker",
    onet_code: "21-1022.00",
    oecd_core_skills: ["Communication", "Judgment", "Social Perceptiveness"],
    neuprint_axes_weights: {
      analyticity: 0.225,
      flow: 0.194,
      metacognition: 0.265,
      authenticity: 0.316,
    },
    min_requirements: { arc_level: 4, authenticity: 0.6 },
  },
  {
    role_code: "BEHAVIORAL_THERAPIST",
    job_id: "behavioral_therapist",
    onet_code: "21-1011.00",
    oecd_core_skills: ["Communication", "Monitoring", "Social Perceptiveness"],
    neuprint_axes_weights: {
      analyticity: 0.223,
      flow: 0.196,
      metacognition: 0.267,
      authenticity: 0.314,
    },
    min_requirements: { arc_level: 4, authenticity: 0.6 },
  },
  {
    role_code: "REHABILITATION_SPECIALIST",
    job_id: "rehabilitation_specialist",
    onet_code: "21-1015.00",
    oecd_core_skills: ["Communication", "Monitoring", "Judgment"],
    neuprint_axes_weights: {
      analyticity: 0.223,
      flow: 0.192,
      metacognition: 0.277,
      authenticity: 0.308,
    },
    min_requirements: { arc_level: 4, authenticity: 0.6 },
  },
  {
    role_code: "EXECUTIVE_LEAD",
    job_id: "ceo_coo_cso",
    onet_code: "11-1011.00",
    oecd_core_skills: ["Decision Making", "Systems Thinking", "Communication"],
    neuprint_axes_weights: {
      analyticity: 0.262,
      flow: 0.205,
      metacognition: 0.261,
      authenticity: 0.272,
    },
    min_requirements: { arc_level: 5, analyticity: 0.5 },
  },
  {
    role_code: "PUBLIC_POLICY_DIRECTOR",
    job_id: "public_policy_director",
    onet_code: "11-9199.00",
    oecd_core_skills: ["Decision Making", "Systems Analysis", "Communication"],
    neuprint_axes_weights: {
      analyticity: 0.316,
      flow: 0.052,
      metacognition: 0.312,
      authenticity: 0.32,
    },
    min_requirements: { arc_level: 5, analyticity: 0.5 },
  },
  {
    role_code: "GOVERNMENT_ADMINISTRATOR",
    job_id: "government_administrator",
    onet_code: "11-3013.00",
    oecd_core_skills: ["Decision Making", "Monitoring", "Communication"],
    neuprint_axes_weights: {
      analyticity: 0.255,
      flow: 0.215,
      metacognition: 0.267,
      authenticity: 0.263,
    },
    min_requirements: { arc_level: 5, analyticity: 0.5 },
  },
  {
    role_code: "PROGRAM_DIRECTOR",
    job_id: "program_director",
    onet_code: "11-9151.00",
    oecd_core_skills: ["Decision Making", "Systems Thinking", "Monitoring"],
    neuprint_axes_weights: {
      analyticity: 0.256,
      flow: 0.211,
      metacognition: 0.273,
      authenticity: 0.26,
    },
    min_requirements: { arc_level: 5, analyticity: 0.5 },
  },
  {
    role_code: "PUBLIC_STRATEGY_LEAD",
    job_id: "public_strategy_lead",
    onet_code: "13-1111.00",
    oecd_core_skills: ["Systems Thinking", "Decision Making", "Communication"],
    neuprint_axes_weights: {
      analyticity: 0.267,
      flow: 0.205,
      metacognition: 0.258,
      authenticity: 0.27,
    },
    min_requirements: { arc_level: 5, analyticity: 0.5 },
  },
  {
    role_code: "MARKETING_STRATEGIST",
    job_id: "marketing_strategist",
    onet_code: "13-1161.00",
    oecd_core_skills: ["Communication", "Decision Making", "Critical Thinking"],
    neuprint_axes_weights: {
      analyticity: 0.248,
      flow: 0.213,
      metacognition: 0.238,
      authenticity: 0.301,
    },
    min_requirements: { arc_level: 3, authenticity: 0.55 },
  },
  {
    role_code: "BRAND_MANAGER",
    job_id: "brand_manager",
    onet_code: "11-2021.00",
    oecd_core_skills: ["Communication", "Decision Making", "Social Perceptiveness"],
    neuprint_axes_weights: {
      analyticity: 0.22,
      flow: 0.219,
      metacognition: 0.244,
      authenticity: 0.317,
    },
    min_requirements: { arc_level: 3, authenticity: 0.55 },
  },
  {
    role_code: "SALES_DIRECTOR",
    job_id: "sales_director",
    onet_code: "11-2022.00",
    oecd_core_skills: ["Communication", "Decision Making", "Social Perceptiveness"],
    neuprint_axes_weights: {
      analyticity: 0.224,
      flow: 0.213,
      metacognition: 0.241,
      authenticity: 0.322,
    },
    min_requirements: { arc_level: 3, authenticity: 0.55 },
  },
  {
    role_code: "PR_MANAGER",
    job_id: "pr_manager",
    onet_code: "11-2032.00",
    oecd_core_skills: ["Communication", "Social Perceptiveness", "Decision Making"],
    neuprint_axes_weights: {
      analyticity: 0.04,
      flow: 0.058,
      metacognition: 0.292,
      authenticity: 0.61,
    },
    min_requirements: { arc_level: 3, authenticity: 0.55 },
  },
  {
    role_code: "COMMUNICATION_MANAGER",
    job_id: "communication_manager",
    onet_code: "11-2032.00",
    oecd_core_skills: ["Communication", "Decision Making", "Writing"],
    neuprint_axes_weights: {
      analyticity: 0.04,
      flow: 0.058,
      metacognition: 0.292,
      authenticity: 0.61,
    },
    min_requirements: { arc_level: 3, authenticity: 0.55 },
  },
  {
    role_code: "MEDIA_PLANNER",
    job_id: "media_planner",
    onet_code: "13-1161.00",
    oecd_core_skills: ["Communication", "Information Processing", "Decision Making"],
    neuprint_axes_weights: {
      analyticity: 0.24,
      flow: 0.221,
      metacognition: 0.238,
      authenticity: 0.301,
    },
    min_requirements: { arc_level: 3, authenticity: 0.55 },
  },
  {
    role_code: "DIGITAL_MARKETER",
    job_id: "digital_marketer",
    onet_code: "13-1161.01",
    oecd_core_skills: ["Communication", "Information Processing", "Decision Making"],
    neuprint_axes_weights: {
      analyticity: 0.235,
      flow: 0.226,
      metacognition: 0.24,
      authenticity: 0.299,
    },
    min_requirements: { arc_level: 3, authenticity: 0.55 },
  },
  {
    role_code: "UX_UI_DESIGNER",
    job_id: "ux_ui_designer",
    onet_code: "27-1024.00",
    oecd_core_skills: ["Communication", "Cognitive Flexibility", "Critical Thinking"],
    neuprint_axes_weights: {
      analyticity: 0.217,
      flow: 0.237,
      metacognition: 0.225,
      authenticity: 0.321,
    },
    min_requirements: { arc_level: 3, authenticity: 0.6 },
  },
  {
    role_code: "GRAPHIC_DESIGNER",
    job_id: "graphic_designer",
    onet_code: "27-1024.00",
    oecd_core_skills: ["Communication", "Writing", "Cognitive Flexibility"],
    neuprint_axes_weights: {
      analyticity: 0.209,
      flow: 0.237,
      metacognition: 0.225,
      authenticity: 0.329,
    },
    min_requirements: { arc_level: 3, authenticity: 0.6 },
  },
  {
    role_code: "VIDEO_PRODUCER",
    job_id: "video_producer",
    onet_code: "27-2012.00",
    oecd_core_skills: ["Communication", "Decision Making", "Cognitive Flexibility"],
    neuprint_axes_weights: {
      analyticity: 0.222,
      flow: 0.237,
      metacognition: 0.229,
      authenticity: 0.312,
    },
    min_requirements: { arc_level: 3, authenticity: 0.6 },
  },
  {
    role_code: "CONTENT_STRATEGIST",
    job_id: "content_strategist",
    onet_code: "13-1161.00",
    oecd_core_skills: ["Writing", "Communication", "Critical Thinking"],
    neuprint_axes_weights: {
      analyticity: 0.238,
      flow: 0.215,
      metacognition: 0.222,
      authenticity: 0.325,
    },
    min_requirements: { arc_level: 3, authenticity: 0.6 },
  },
  {
    role_code: "CREATIVE_DIRECTOR",
    job_id: "creative_director",
    onet_code: "11-2011.00",
    oecd_core_skills: ["Communication", "Decision Making", "Cognitive Flexibility"],
    neuprint_axes_weights: {
      analyticity: 0.212,
      flow: 0.224,
      metacognition: 0.23,
      authenticity: 0.334,
    },
    min_requirements: { arc_level: 3, authenticity: 0.6 },
  },
  {
    role_code: "EDITOR",
    job_id: "editor",
    onet_code: "27-3041.00",
    oecd_core_skills: ["Writing", "Critical Thinking", "Communication"],
    neuprint_axes_weights: {
      analyticity: 0.216,
      flow: 0.22,
      metacognition: 0.224,
      authenticity: 0.34,
    },
    min_requirements: { arc_level: 3, authenticity: 0.6 },
  },
  {
    role_code: "MULTIMEDIA_ARTIST",
    job_id: "multimedia_artist",
    onet_code: "27-1014.00",
    oecd_core_skills: ["Communication", "Cognitive Flexibility", "Writing"],
    neuprint_axes_weights: {
      analyticity: 0.222,
      flow: 0.234,
      metacognition: 0.23,
      authenticity: 0.314,
    },
    min_requirements: { arc_level: 3, authenticity: 0.6 },
  },
  {
    role_code: "PHYSICIAN",
    job_id: "physician",
    onet_code: "29-1218.00",
    oecd_core_skills: ["Judgment", "Monitoring", "Communication"],
    neuprint_axes_weights: {
      analyticity: 0.253,
      flow: 0.209,
      metacognition: 0.283,
      authenticity: 0.255,
    },
    min_requirements: { arc_level: 4, metacognition: 0.55 },
  },
  {
    role_code: "NURSE",
    job_id: "nurse",
    onet_code: "29-1141.00",
    oecd_core_skills: ["Monitoring", "Judgment", "Communication"],
    neuprint_axes_weights: {
      analyticity: 0.249,
      flow: 0.212,
      metacognition: 0.28,
      authenticity: 0.259,
    },
    min_requirements: { arc_level: 4, metacognition: 0.55 },
  },
  {
    role_code: "MEDICAL_RESEARCHER",
    job_id: "medical_researcher",
    onet_code: "19-1042.00",
    oecd_core_skills: ["Critical Thinking", "Active Learning", "Systems Analysis"],
    neuprint_axes_weights: {
      analyticity: 0.275,
      flow: 0.206,
      metacognition: 0.274,
      authenticity: 0.245,
    },
    min_requirements: { arc_level: 4, metacognition: 0.55 },
  },
  {
    role_code: "CLINICAL_DATA_MANAGER",
    job_id: "clinical_data_manager",
    onet_code: "11-9121.00",
    oecd_core_skills: ["Information Processing", "Monitoring", "Critical Thinking"],
    neuprint_axes_weights: {
      analyticity: 0.259,
      flow: 0.198,
      metacognition: 0.282,
      authenticity: 0.261,
    },
    min_requirements: { arc_level: 4, metacognition: 0.55 },
  },
  {
    role_code: "BIOMEDICAL_SCIENTIST",
    job_id: "biomedical_scientist",
    onet_code: "19-1042.00",
    oecd_core_skills: ["Critical Thinking", "Systems Analysis", "Active Learning"],
    neuprint_axes_weights: {
      analyticity: 0.275,
      flow: 0.206,
      metacognition: 0.274,
      authenticity: 0.245,
    },
    min_requirements: { arc_level: 4, analyticity: 0.55, metacognition: 0.55 },
  },
  {
    role_code: "PUBLIC_HEALTH_ANALYST",
    job_id: "public_health_analyst",
    onet_code: "19-1041.00",
    oecd_core_skills: ["Critical Thinking", "Systems Analysis", "Communication"],
    neuprint_axes_weights: {
      analyticity: 0.28,
      flow: 0.199,
      metacognition: 0.268,
      authenticity: 0.253,
    },
    min_requirements: { arc_level: 4, analyticity: 0.55, metacognition: 0.55 },
  },
  {
    role_code: "LAWYER",
    job_id: "lawyer",
    onet_code: "23-1011.00",
    oecd_core_skills: ["Critical Thinking", "Judgment", "Writing"],
    neuprint_axes_weights: {
      analyticity: 0.276,
      flow: 0.185,
      metacognition: 0.269,
      authenticity: 0.27,
    },
    min_requirements: { arc_level: 4, analyticity: 0.55 },
  },
  {
    role_code: "LEGAL_RESEARCHER",
    job_id: "legal_researcher",
    onet_code: "23-1011.00",
    oecd_core_skills: ["Critical Thinking", "Writing", "Information Processing"],
    neuprint_axes_weights: {
      analyticity: 0.277,
      flow: 0.192,
      metacognition: 0.261,
      authenticity: 0.27,
    },
    min_requirements: { arc_level: 4, analyticity: 0.55 },
  },
  {
    role_code: "COMPLIANCE_MANAGER",
    job_id: "compliance_manager",
    onet_code: "11-9199.00",
    oecd_core_skills: ["Monitoring", "Judgment", "Writing"],
    neuprint_axes_weights: {
      analyticity: 0.08,
      flow: 0.032,
      metacognition: 0.573,
      authenticity: 0.315,
    },
    min_requirements: { arc_level: 4, analyticity: 0.55 },
  },
  {
    role_code: "ETHICS_OFFICER",
    job_id: "ethics_officer",
    onet_code: "13-1041.00",
    oecd_core_skills: ["Judgment", "Communication", "Monitoring"],
    neuprint_axes_weights: {
      analyticity: 0.263,
      flow: 0.194,
      metacognition: 0.277,
      authenticity: 0.266,
    },
    min_requirements: { arc_level: 4, analyticity: 0.55 },
  },
  {
    role_code: "REGULATORY_AFFAIRS_SPECIALIST",
    job_id: "regulatory_affairs_specialist",
    onet_code: "13-1041.07",
    oecd_core_skills: ["Monitoring", "Writing", "Judgment"],
    neuprint_axes_weights: {
      analyticity: 0.275,
      flow: 0.186,
      metacognition: 0.276,
      authenticity: 0.263,
    },
    min_requirements: { arc_level: 4, analyticity: 0.55 },
  },
  {
    role_code: "CONTRACT_SPECIALIST",
    job_id: "contract_specialist",
    onet_code: "13-1023.00",
    oecd_core_skills: ["Writing", "Critical Thinking", "Judgment"],
    neuprint_axes_weights: {
      analyticity: 0.274,
      flow: 0.188,
      metacognition: 0.272,
      authenticity: 0.266,
    },
    min_requirements: { arc_level: 4, analyticity: 0.55 },
  },
  {
    role_code: "OPERATIONS_MANAGER",
    job_id: "operations_manager",
    onet_code: "11-1021.00",
    oecd_core_skills: ["Monitoring", "Decision Making", "Systems Thinking"],
    neuprint_axes_weights: {
      analyticity: 0.258,
      flow: 0.224,
      metacognition: 0.266,
      authenticity: 0.252,
    },
    min_requirements: { arc_level: 3, flow: 0.5 },
  },
  {
    role_code: "QUALITY_MANAGER",
    job_id: "quality_manager",
    onet_code: "11-3051.00",
    oecd_core_skills: ["Monitoring", "Critical Thinking", "Decision Making"],
    neuprint_axes_weights: {
      analyticity: 0.267,
      flow: 0.23,
      metacognition: 0.269,
      authenticity: 0.234,
    },
    min_requirements: { arc_level: 3, flow: 0.5 },
  },
  {
    role_code: "SAFETY_ENGINEER",
    job_id: "safety_engineer",
    onet_code: "17-2111.00",
    oecd_core_skills: ["Monitoring", "Judgment", "Systems Analysis"],
    neuprint_axes_weights: {
      analyticity: 0.277,
      flow: 0.238,
      metacognition: 0.257,
      authenticity: 0.228,
    },
    min_requirements: { arc_level: 3, analyticity: 0.55, flow: 0.5 },
  },
  {
    role_code: "PROCESS_ANALYST",
    job_id: "process_analyst",
    onet_code: "13-1111.00",
    oecd_core_skills: ["Systems Analysis", "Monitoring", "Critical Thinking"],
    neuprint_axes_weights: {
      analyticity: 0.289,
      flow: 0.22,
      metacognition: 0.251,
      authenticity: 0.24,
    },
    min_requirements: { arc_level: 3, analyticity: 0.55, flow: 0.5 },
  },
  {
    role_code: "SUPPLY_CHAIN_ANALYST",
    job_id: "supply_chain_analyst",
    onet_code: "13-1081.00",
    oecd_core_skills: ["Systems Analysis", "Monitoring", "Decision Making"],
    neuprint_axes_weights: {
      analyticity: 0.279,
      flow: 0.227,
      metacognition: 0.259,
      authenticity: 0.235,
    },
    min_requirements: { arc_level: 3, analyticity: 0.55, flow: 0.5 },
  },
  {
    role_code: "LOGISTICS_PLANNER",
    job_id: "logistics_planner",
    onet_code: "13-1081.00",
    oecd_core_skills: ["Systems Analysis", "Time Sharing", "Decision Making"],
    neuprint_axes_weights: {
      analyticity: 0.274,
      flow: 0.237,
      metacognition: 0.252,
      authenticity: 0.237,
    },
    min_requirements: { arc_level: 3, flow: 0.5 },
  },
  {
    role_code: "INVESTMENT_ANALYST",
    job_id: "investment_analyst",
    onet_code: "13-2051.00",
    oecd_core_skills: ["Critical Thinking", "Decision Making", "Monitoring"],
    neuprint_axes_weights: {
      analyticity: 0.355,
      flow: 0.035,
      metacognition: 0.562,
      authenticity: 0.048,
    },
    min_requirements: { arc_level: 4, analyticity: 0.6 },
  },
  {
    role_code: "PORTFOLIO_MANAGER",
    job_id: "portfolio_manager",
    onet_code: "13-2052.00",
    oecd_core_skills: ["Decision Making", "Monitoring", "Critical Thinking"],
    neuprint_axes_weights: {
      analyticity: 0.293,
      flow: 0.189,
      metacognition: 0.267,
      authenticity: 0.251,
    },
    min_requirements: { arc_level: 4, analyticity: 0.6 },
  },
  {
    role_code: "CREDIT_ANALYST",
    job_id: "credit_analyst",
    onet_code: "13-2041.00",
    oecd_core_skills: ["Judgment", "Critical Thinking", "Monitoring"],
    neuprint_axes_weights: {
      analyticity: 0.307,
      flow: 0.199,
      metacognition: 0.268,
      authenticity: 0.226,
    },
    min_requirements: { arc_level: 4, analyticity: 0.6 },
  },
  {
    role_code: "ACTUARY",
    job_id: "actuary",
    onet_code: "15-2011.00",
    oecd_core_skills: ["Critical Thinking", "Information Processing", "Decision Making"],
    neuprint_axes_weights: {
      analyticity: 0.317,
      flow: 0.197,
      metacognition: 0.257,
      authenticity: 0.229,
    },
    min_requirements: { arc_level: 4, analyticity: 0.6 },
  },
  {
    role_code: "INSURANCE_UNDERWRITER",
    job_id: "insurance_underwriter",
    onet_code: "13-2053.00",
    oecd_core_skills: ["Judgment", "Monitoring", "Decision Making"],
    neuprint_axes_weights: {
      analyticity: 0.286,
      flow: 0.193,
      metacognition: 0.278,
      authenticity: 0.243,
    },
    min_requirements: { arc_level: 4, analyticity: 0.6 },
  },
  {
    role_code: "TREASURY_MANAGER",
    job_id: "treasury_manager",
    onet_code: "11-3031.00",
    oecd_core_skills: ["Decision Making", "Monitoring", "Information Processing"],
    neuprint_axes_weights: {
      analyticity: 0.282,
      flow: 0.199,
      metacognition: 0.271,
      authenticity: 0.248,
    },
    min_requirements: { arc_level: 4, analyticity: 0.6 },
  },
  {
    role_code: "HR_MANAGER",
    job_id: "hr_manager",
    onet_code: "11-3121.00",
    oecd_core_skills: ["Communication", "Decision Making", "Social Perceptiveness"],
    neuprint_axes_weights: {
      analyticity: 0.22,
      flow: 0.207,
      metacognition: 0.272,
      authenticity: 0.301,
    },
    min_requirements: { arc_level: 3, authenticity: 0.55 },
  },
  {
    role_code: "TALENT_MANAGER",
    job_id: "talent_manager",
    onet_code: "11-3121.00",
    oecd_core_skills: ["Communication", "Judgment", "Social Perceptiveness"],
    neuprint_axes_weights: {
      analyticity: 0.22,
      flow: 0.207,
      metacognition: 0.272,
      authenticity: 0.301,
    },
    min_requirements: { arc_level: 3, authenticity: 0.55 },
  },
  {
    role_code: "ORGANIZATIONAL_DEVELOPMENT_MANAGER",
    job_id: "organizational_development_manager",
    onet_code: "13-1151.00",
    oecd_core_skills: ["Systems Thinking", "Communication", "Judgment"],
    neuprint_axes_weights: {
      analyticity: 0.219,
      flow: 0.207,
      metacognition: 0.279,
      authenticity: 0.295,
    },
    min_requirements: { arc_level: 3, authenticity: 0.55 },
  },
  {
    role_code: "CULTURE_MANAGER",
    job_id: "culture_manager",
    onet_code: "11-3121.00",
    oecd_core_skills: ["Communication", "Social Perceptiveness", "Judgment"],
    neuprint_axes_weights: {
      analyticity: 0.22,
      flow: 0.207,
      metacognition: 0.272,
      authenticity: 0.301,
    },
    min_requirements: { arc_level: 3, authenticity: 0.55 },
  },
  {
    role_code: "RECRUITER",
    job_id: "recruiter",
    onet_code: "13-1071.00",
    oecd_core_skills: ["Communication", "Social Perceptiveness", "Decision Making"],
    neuprint_axes_weights: {
      analyticity: 0.224,
      flow: 0.194,
      metacognition: 0.27,
      authenticity: 0.312,
    },
    min_requirements: { arc_level: 3, authenticity: 0.55 },
  },
  {
    role_code: "LEARNING_AND_DEVELOPMENT_SPECIALIST",
    job_id: "learning_and_development_specialist",
    onet_code: "13-1151.00",
    oecd_core_skills: ["Learning to Learn", "Communication", "Judgment"],
    neuprint_axes_weights: {
      analyticity: 0.217,
      flow: 0.209,
      metacognition: 0.283,
      authenticity: 0.291,
    },
    min_requirements: { arc_level: 3, authenticity: 0.55 },
  },
  {
    role_code: "RPA_AGENT",
    job_id: "rpa_agent",
    onet_code: "15-1252.00",
    oecd_core_skills: ["Time Sharing", "Information Processing", "Monitoring"],
    neuprint_axes_weights: {
      analyticity: 0.261,
      flow: 0.274,
      metacognition: 0.242,
      authenticity: 0.223,
    },
    min_requirements: { arc_level: 2, flow: 0.55 },
  },
  {
    role_code: "CHATBOT_OPERATOR",
    job_id: "chatbot_operator",
    onet_code: "15-1252.00",
    oecd_core_skills: ["Communication", "Monitoring", "Information Processing"],
    neuprint_axes_weights: {
      analyticity: 0.261,
      flow: 0.266,
      metacognition: 0.242,
      authenticity: 0.231,
    },
    min_requirements: { arc_level: 2, flow: 0.55 },
  },
  {
    role_code: "AUTOMATED_QA_BOT",
    job_id: "automated_qa_bot",
    onet_code: "15-1253.00",
    oecd_core_skills: ["Monitoring", "Information Processing", "Critical Thinking"],
    neuprint_axes_weights: {
      analyticity: 0.267,
      flow: 0.27,
      metacognition: 0.24,
      authenticity: 0.223,
    },
    min_requirements: { arc_level: 2, flow: 0.55 },
  },
  {
    role_code: "REPORT_GENERATION_AGENT",
    job_id: "report_generation_agent",
    onet_code: "15-1252.00",
    oecd_core_skills: ["Writing", "Information Processing", "Monitoring"],
    neuprint_axes_weights: {
      analyticity: 0.261,
      flow: 0.266,
      metacognition: 0.242,
      authenticity: 0.231,
    },
    min_requirements: { arc_level: 2, flow: 0.55 },
  },
  {
    role_code: "MONITORING_AI",
    job_id: "monitoring_ai",
    onet_code: "15-1212.00",
    oecd_core_skills: ["Monitoring", "Time Sharing", "Information Processing"],
    neuprint_axes_weights: {
      analyticity: 0.254,
      flow: 0.277,
      metacognition: 0.241,
      authenticity: 0.228,
    },
    min_requirements: { arc_level: 2, flow: 0.55 },
  },
];

export default ROLE_CONFIGS_FULL_V3;
